services:
  ui:
    build: .
    image: senior-design-app:latest
    ports:
      - "8501:8501"
    volumes:
      - senior_design_data:/app/data
      - ./results_cache:/app/results_cache

volumes:
  senior_design_data: